services:
  user-service:
    build:
      context: ../../ # Contexte depuis backend/
      dockerfile: services/user/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URI
      - DIRECT_URL
      - JWT_SECRET
