name: Essenz+ Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout @ 1.0.0
    - name: Install dependencies
      run:   npm install
    - name: Run tests
      run: npm test
    - name: Build
      run: npm run build

      env:
        NODE_ENV: production
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  

